### ISSUE TITLE
Config breaking on reload

### ISSUE THREAD

**Issue by bMacSwigg** [morganecf/jitsi-party#157]
When I reload the page client-side (connected to my dev instance), it fails to load the config and I see the following flask error:

```
Traceback (most recent call last):
  File "/home/brian_mcswiggen/jitsi-party/venv/lib/python3.7/site-packages/flask_socketio/__init__.py", line 46, in __call__ 
    start_response)
  File "/home/brian_mcswiggen/jitsi-party/venv/lib/python3.7/site-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/brian_mcswiggen/jitsi-party/venv/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/brian_mcswiggen/jitsi-party/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/brian_mcswiggen/jitsi-party/venv/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/brian_mcswiggen/jitsi-party/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/brian_mcswiggen/jitsi-party/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/brian_mcswiggen/jitsi-party/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/brian_mcswiggen/jitsi-party/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/brian_mcswiggen/jitsi-party/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/brian_mcswiggen/jitsi-party/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/brian_mcswiggen/jitsi-party/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/brian_mcswiggen/jitsi-party/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/brian_mcswiggen/jitsi-party/app/jitsi/main.py", line 46, in get_config
    if room['type'] == 'imagemap' and image_map in image_maps:
TypeError: unhashable type: 'dict'
```

The error seems to indicate that the value of `image_map` is a dict somehow.

This only happens on reload; the first time I connect after creating the db and running flask it works fine.

I'm going to try to look into this further in case it's caused by bad configuration on my side somehow.

**Comment by bMacSwigg** [comment]
This seems to be fixed by #158
