### ISSUE TITLE
Web logs still full of tracebacks

### ISSUE THREAD

**Issue by hndrewaall** [morganecf/jitsi-party#237]
```
web-worker_1_1  | NameError: name 'room' is not defined
web-worker_1_1  |
web-worker_1_1  | Exception in thread Thread-7337:
web-worker_1_1  | Traceback (most recent call last):
web-worker_1_1  |   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
web-worker_1_1  |     self.run()
web-worker_1_1  |   File "/usr/local/lib/python3.7/threading.py", line 870, in run
web-worker_1_1  |     self._target(*self._args, **self._kwargs)
web-worker_1_1  |   File "/usr/local/lib/python3.7/site-packages/socketio/server.py", line 679, in _handle_event_internal
web-worker_1_1  |     r = server._trigger_event(data[0], namespace, sid, *data[1:])
web-worker_1_1  |   File "/usr/local/lib/python3.7/site-packages/socketio/server.py", line 708, in _trigger_event
web-worker_1_1  |     return self.handlers[namespace][event](*args)
web-worker_1_1  |   File "/usr/local/lib/python3.7/site-packages/flask_socketio/__init__.py", line 283, in _handler
web-worker_1_1  |     *args)
web-worker_1_1  |   File "/usr/local/lib/python3.7/site-packages/flask_socketio/__init__.py", line 713, in _handle_event
web-worker_1_1  |     ret = handler(*args)
web-worker_1_1  |   File "/app/jitsi/events.py", line 30, in on_leave_room
web-worker_1_1  |     User.leave_room(message['user']['id'], message['room'])
web-worker_1_1  |   File "/app/jitsi/models.py", line 55, in leave_room
web-worker_1_1  |     if not user.room:
web-worker_1_1  | AttributeError: 'NoneType' object has no attribute 'room'
```

Tracebacks like this fill up logs, which is very noisy. Moreover, we have no timestamps associated with these, which sucks. We should look at our exception handling/logger config.

**Comment by hndrewaall** [comment]
Not much of an issue anymore, for whatever reason
